export const data = [
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "AirX Media",
        "ParentID": "4df7054d-60d4-46aa-8355-906a9b0a17f1",
        "ProductID": "cd2e3c7f-0722-41cf-aa97-3d8b23e8da45",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "AirX Media",
        "descriptionru": "AirX Media",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "AirX Media",
        "ParentID": null,
        "ProductID": "4df7054d-60d4-46aa-8355-906a9b0a17f1",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_21_2",
        "descriptionen": "AirX Media",
        "descriptionru": "AirX Media",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "AirX Play",
        "ParentID": "78f3f373-82c4-49ea-b9a2-661dbbc55f81",
        "ProductID": "e39e8af2-31ee-4c52-8fb8-7d76f3e31db4",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "AirX Play",
        "descriptionru": "AirX Play",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": null,
        "Name": "AirX Play",
        "ParentID": null,
        "ProductID": "78f3f373-82c4-49ea-b9a2-661dbbc55f81",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_31",
        "descriptionen": "AirX Play",
        "descriptionru": "AirX Play",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "AirX Record",
        "ParentID": null,
        "ProductID": "1a67a379-2fb6-4141-a7de-8c076e7a4148",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_12",
        "descriptionen": "AirX Record",
        "descriptionru": "AirX Record",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Alarm - Video artifacts detected",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "072652f4-6ec4-41c8-b263-5cfb2ddb501d",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Module for detection of video artifacts in the incoming video stream",
        "descriptionru": "Модуль выявления артефактов видео во входном видеопотоке",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Alarms - Service EIT Gap and Service EIT Intersection",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "8d9d673c-de43-4b4a-bda6-589cf11fd536",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Module for detection of time inconsistencies between scheduled events in EIT table",
        "descriptionru": "Модуль выявления временных несоответствий между событиями по расписанию в таблице EIT",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "AlphaSDI HD - driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "a887e352-5aac-448e-810f-d4bfadff29d5",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for AlphaSDI HD",
        "descriptionru": "Драйвера для платы AlphaSDI HD",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "AlphaSDI HD - firmware",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "c61e5164-de17-493b-8886-a4bfc7a88d88",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "Firmware for AlphaSDI HD",
        "descriptionru": "Прошивки для платы AlphaSDI HD",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": null,
        "Name": "ASMTRV",
        "ParentID": null,
        "ProductID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_34",
        "descriptionen": "Monitoring quality of TV/radio content delivery across the whole distribution network",
        "descriptionru": "Контроль качества передачи ТВ и радио сигнала во всей сети вещания",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "ATest Prod",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "85200fa6-38fa-45fa-a8dd-6ac8432c9089",
        "Relation": null,
        "Type": "hardware",
        "colorscheme": "scheme_default",
        "descriptionen": "111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "BTesting Product",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "63601d86-572b-458c-a4d7-183a2eccec40",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "12345",
        "descriptionru": "12345",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "CryptoKey",
        "ParentID": null,
        "ProductID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_41",
        "descriptionen": "Software licensing subsystem",
        "descriptionru": "Подсистема лицензирования ПО",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "CryptoKey Identifier",
        "ParentID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "ProductID": "155a8451-28e5-4757-af6f-76be9d090c30",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Utility to get USB CryptoKey identification information.",
        "descriptionru": "Утилита для получения идентификатора ключа.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "CryptoKey License Server",
        "ParentID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "ProductID": "59c328cd-c022-40ca-94fd-6e48e7b45329",
        "Relation": "59c328cd-c022-40ca-94fd-6e48e7b45329",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Licensing server to share same usb key between multiple Stream Labs applications installed on multiple servers.",
        "descriptionru": "Сервер лицензирования для соместного доступа к одному USB ключу ПО StreamLabs с нескольких серверов.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "CryptoKey License Server documentation",
        "ParentID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "ProductID": "49d0dbc6-e080-4d6d-ae97-3e17abca87eb",
        "Relation": "59c328cd-c022-40ca-94fd-6e48e7b45329",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream Labs License Server documentation",
        "descriptionru": "Документация на Stream Labs License Server",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "CTestproduct2",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "022d6643-7173-439f-a082-2c7d03ebafbf",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "ё11222",
        "descriptionru": "22222",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "DekTec Driver",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "58e78096-ff72-454d-aaf2-2183f0223b2e",
        "Relation": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "DekTec Driver v1.14.0, DtInfo v4.30.0",
        "descriptionru": "DekTec Driver v1.14.0, DtInfo v4.30.0",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "Description of USB GPIO",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "94fa90a9-9380-42a1-86fc-fe497f912f7d",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of USB GPIO",
        "descriptionru": "Документация по устройствам USB GPIO",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "Description of video cards",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "a45896d2-0034-4349-bdd4-23ddea06a050",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of video cards",
        "descriptionru": "Описание видеоплат",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Desktop Video Windows",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "f3965a3a-29f0-4b16-aaf8-40163675591b",
        "Relation": "fb34b210-05bc-40e6-9fc2-95c412c68317",
        "Type": "driver",
        "colorscheme": null,
        "descriptionen": "DeckLink recommended driver version",
        "descriptionru": "Рекомендованная версия драйвера DeckLink",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Desktop Video Windows 11.0",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "2068644b-04b9-4a27-9903-acc1ec7c2f96",
        "Relation": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "BlackMagic Driver",
        "descriptionru": "BlackMagic Driver",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Desktop Video Windows 12.2.2",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "5373c4c3-a3cc-4c39-bc4b-e66a5850d5ce",
        "Relation": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Blackmagic Driver",
        "descriptionru": "Blackmagic Driver",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Documents",
        "ParentID": "26c12ca4-1443-4295-8f32-12b2239d1fbe",
        "ProductID": "09507cde-9b5b-4e73-9a90-441c3a763a7a",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Short product description should be located here",
        "descriptionru": "Краткое описание продукта должно находиться здесь",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Firmware",
        "ParentID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "ProductID": "c344b5fd-42c4-44c0-bfbe-72f4a213e728",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": null,
        "descriptionen": "Firmware for FM Probe",
        "descriptionru": "Прошивка для FM Probe",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "Firmware & Drivers & SDK",
        "ParentID": null,
        "ProductID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_30",
        "descriptionen": "Firmware and Software for computer peripherals manufactured by Stream Labs",
        "descriptionru": "Прошивки и программное обеспечение для периферийных устройств производимых компанией Stream Labs",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "FM Probe",
        "ParentID": null,
        "ProductID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_38",
        "descriptionen": "Very compact multichannel probe for FM monitoring in cyclic mode",
        "descriptionru": "Миниатюрный проб для мониторинга FM-вещания в циклическом режиме",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Kuku Test Product",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "0006cc02-23aa-45c8-bc5f-a1b27b1bbbdb",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "3333",
        "descriptionru": "33333",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MH4LM - driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "5efb70c5-5fc3-4bd7-b638-622b1a749c26",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for MH4LM (old firmware)",
        "descriptionru": "Драйвера для линейки плат MH4LM со старыми прошивками",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MH4LM - firmware",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "42aa4049-56af-4b82-94f0-d00c140d7123",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "Firmware for MH4LM line",
        "descriptionru": "Прошивки для линейки плат MH4LM",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MH8 - firmware",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "3dd09a12-0afd-45ae-9562-07bb6d475a97",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "Firmware for MH8",
        "descriptionru": "Прошивки для платы MH8",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MIB Files",
        "ParentID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "ProductID": "870d0b0b-439c-472c-ad26-4e4913e59f3e",
        "Relation": "bed9125a-a1b3-4cc9-8a0a-20af1b2dfc1c",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "MIB files for T2MI Splitter SNMP Agent",
        "descriptionru": "MIB файлы для SNMP агента  службы  T2MI Splitter.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MS2/MS4 - driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "1faeee3b-3323-4fb4-81c4-4d26f3ea3761",
        "Relation": "f19ff516-e0c1-4739-8e1c-a6794155f5f3",
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for MS2/MS4 (old firmware)",
        "descriptionru": "Драйвера для плат MS2/MS4 со старыми прошивками",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MS2/MS4 - firmware",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "f19ff516-e0c1-4739-8e1c-a6794155f5f3",
        "Relation": "313ce28a-10d8-4d39-ada8-4149ec039b52",
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "Firmware for MS2/MS4",
        "descriptionru": "Прошивки для плат MS2/MS4",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MS-416 - driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "1d77ab64-7c35-4a76-93ec-6b635a193343",
        "Relation": "7d203f7a-a748-43fc-a014-c2852832937f",
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for MS-416 (old firmware)",
        "descriptionru": "Драйвера для платы MS-416 со старой прошивкой",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "MS-416 - firmware",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "7d203f7a-a748-43fc-a014-c2852832937f",
        "Relation": "313ce28a-10d8-4d39-ada8-4149ec039b52",
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "Firmware for MS-416 line",
        "descriptionru": "Прошивки для линейки плат MS-416",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Multiencoder",
        "ParentID": "f53eb514-b355-41d8-805c-df3cb2dc26dc",
        "ProductID": "79f5bc2d-d7f7-45f3-a417-ab9a812b42ce",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Application for create transport stream from a SDI source (MS2/4, MH4LM)",
        "descriptionru": "Приложение для формирования транспортного потока из SDI (MS2/4, MH4LM)",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "Multiencoder",
        "ParentID": null,
        "ProductID": "f53eb514-b355-41d8-805c-df3cb2dc26dc",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_48",
        "descriptionen": "Application for create a transport stream from a SDI source  (MS2/4, MH4LM)",
        "descriptionru": "Приложение для формирования транспортного потока из SDI (MS2/4, MH4LM)",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "MultiEncoder / HLS Server",
        "ParentID": null,
        "ProductID": "26c12ca4-1443-4295-8f32-12b2239d1fbe",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_31",
        "descriptionen": "Hardware-software solution for real-time encoding of AV content and broadcasting over HLS",
        "descriptionru": "Аппаратно-программный комплекс для кодирования аудио/видео и вещания через протокол HLS",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MultiMonitor",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "MultiMonitor application allows managing of  all servers in the network, creating of Screen Views for MultiViewers, loading events from database for preview, watching of  channels’ statuses, redirecting channels with problems to Penalty Server.",
        "descriptionru": "Приложение MultiMonitor позволяет контролировать все серверы в сети, создавать раскладки для мультиэкранного процессора, загружать события из базы данных для предпросмотра, просматривать статус каналов, вывод проблемных каналов на Penalty Server и т.д.",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": null,
        "Name": "MultiProbe",
        "ParentID": null,
        "ProductID": "67b5089e-8336-43ce-85ee-c026fb9bc196",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_44",
        "descriptionen": "MultiProbe",
        "descriptionru": "Комплексная система автоматизированного распределенного мониторинга и оперативного контроля качества предоставления услуг",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": null,
        "Name": "MultiRec",
        "ParentID": null,
        "ProductID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_33",
        "descriptionen": "Schedule-based multichannel TV and Radio recording and fast content searching in archives",
        "descriptionru": "Многоканальная запись ТВ и радио сигнала по расписанию и быстрый поиск контента в архивах",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "MultiRec  ADS Scanner / Руководство пользователя.",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "499ff02c-0a04-4839-8579-b6d97a425f48",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "MultiRec ADS Scanner",
        "descriptionru": "Блок поиска рекламы.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MultiRec Server",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Server part of the MultiRec solution for non-stop recording and Advertisement scanning\\detection.",
        "descriptionru": "Серверная часть решения для циклической \"полицейской\" записи теле и радио каналов и детектирования рекламы.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "MultiRec Transcoder / Руководство пользователя.",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "8e47db6e-23de-41ba-a031-a5ed6f0407c1",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "MultiRec Transcoder manual",
        "descriptionru": "MultiRec Transcoder — модуль сервера позволяющим транскодировать транспортный поток со скалированием, уменьшением битрэйта, прожигом тайм кода и текста",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MultiRec WEB UI",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "f2071b79-25aa-4ef8-ab3d-24b5a4703481",
        "Relation": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Type": "software",
        "colorscheme": null,
        "descriptionen": "Short product description should be located here",
        "descriptionru": "Краткое описание продукта должно находиться здесь",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MultiScreen",
        "ParentID": null,
        "ProductID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_36",
        "descriptionen": "Visual and software-based quality monitoring of digital/analog TV & radio broadcasts",
        "descriptionru": "Визуальный и инструментальный контроль качества цифровых и аналоговых ТВ и радио сигналов",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "MultiScreen Server",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "fb34b210-05bc-40e6-9fc2-95c412c68317",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream MultiScreen system is intended for simultaneous visual and instrumental monitoring of multiple video and audio sources in real-time using one or several LCD-panels in poly-screen mode.",
        "descriptionru": "Система Stream MultiScreen предназначена для решения задач по визуальному и инструментальному контролю различных видео и аудио источников в реальном времени на одном или нескольких LCD экранах в полиэкранном режиме.",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "MultiTuner",
        "ParentID": null,
        "ProductID": "b2f531aa-46f9-472c-9405-a17d2db27c19",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_2",
        "descriptionen": "16-channel FM Radio Monitoring Receiver",
        "descriptionru": "16-channel FM Radio Monitoring Receiver",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Notification Service",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "18071506-3b00-403e-89bc-ff7d1517f626",
        "Relation": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Notification Service user manual",
        "descriptionru": "Руководство пользователя /  Notification Service",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "redistributable pack",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "60d0715e-3106-4bd0-8a2b-7e5570e5b0db",
        "Relation": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "redistributable for installation on windows server 2012",
        "descriptionru": "redistributable для установки на windows server 2012",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Release 7.6",
        "ParentID": "67b5089e-8336-43ce-85ee-c026fb9bc196",
        "ProductID": "f23cae79-fc5f-4f24-9898-876161d84109",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Release 7.6",
        "descriptionru": "Release 7.6",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Remote license update",
        "ParentID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "ProductID": "03f6282d-05c7-4715-9df1-ad98288fca2e",
        "Relation": "155a8451-28e5-4757-af6f-76be9d090c30",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Remote license update for StreamLabs USB crypto key",
        "descriptionru": "Удаленное обновление лицензии на USB крипто ключе StreamLabs",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "SDK & Tools for Windows OS",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "6ed44fde-88b5-4d3f-9c76-e8d7fafb8de1",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream Labs SDK with C++ code samples and test utilities binaries. ",
        "descriptionru": "Пакет для разработки программ с примерами кода на C++ и тестовыми утилитам в бинарном виде",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Server",
        "ParentID": "26c12ca4-1443-4295-8f32-12b2239d1fbe",
        "ProductID": "15f26a5f-f29d-47fc-ad07-13d457820bea",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Short product description should be located here",
        "descriptionru": "Краткое описание продукта должно находиться здесь",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Service Rotator",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "905dbffa-3068-43df-b53a-1b598cf0f1fb",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "How to set up and use Service Rotator tool",
        "descriptionru": "Как настроить и использовать Ротатор Сервисов",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "SNMP Agent",
        "ParentID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "ProductID": "bed9125a-a1b3-4cc9-8a0a-20af1b2dfc1c",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "T2MI Splitter SNMP agent module used to process SNMP requests",
        "descriptionru": "SNMP агент для сервиса T2MI Splitter. SNMP агент может быть использован как вспомогательное средство для интеграции T2MI Splitter во внешние системы мониторинга.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "SNMP Agent",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "d1b35c10-d256-4b0f-81af-68b2323751c1",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "SNMP Agent — software which runs on managed devices.",
        "descriptionru": "SNMP агент — программное обеспечение, запускаемое на управляемом устройстве, либо на устройстве, подключенном к интерфейсу управления управляемого устройства.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "SNMP Agent User manual",
        "ParentID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "ProductID": "a35568f1-f5ec-49f8-840e-21a7a0ab298b",
        "Relation": "bed9125a-a1b3-4cc9-8a0a-20af1b2dfc1c",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "SNMP Agent User manual",
        "descriptionru": "Руководство пользователя SNMP Agent",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "SNMP Collector",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "618afd24-fdf7-4401-aa9c-011d8ef31a2f",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Module SNMP Collector allows receiving of various data from external devices using SNMP protocol.",
        "descriptionru": "Модуль SNMP Collector позволяет принимать различные данные от внешних устройств, используя SNMP protocol.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Software Update",
        "ParentID": "b2f531aa-46f9-472c-9405-a17d2db27c19",
        "ProductID": "8b5d8134-3e6f-47b3-a5b6-9c4fc15c2c06",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Software update for MultiTuner",
        "descriptionru": "Пакет обновления ПО для MultiTuner",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Software Update",
        "ParentID": "00c76d0d-8485-4ed3-a51a-593652840fb2",
        "ProductID": "9b240338-122c-48e1-8eaf-f3ed62755365",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "TS Analyzer software update package",
        "descriptionru": "Пакет обновления ПО для TS Analyzer",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "StratoView",
        "ParentID": null,
        "ProductID": "9764c096-daf4-4c51-9ea1-3ccf3716293a",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_9",
        "descriptionen": "StratoView",
        "descriptionru": "StratoView",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Stream MultiRec SNMP Agent",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "92d562dd-7a2c-437c-bc5b-09cf59a57722",
        "Relation": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream MultiRec server SNMP Agent. Extension module used to export server state using SNMP protocol.",
        "descriptionru": "Агент SNMP - модуль расширения для экспорта состояния сервера MultiRec по протоколу SNMP.",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "StreamMultiplex",
        "ParentID": null,
        "ProductID": "0157410c-7510-46ac-a86c-f34403995e95",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_15",
        "descriptionen": "Stream Multiplex",
        "descriptionru": "Stream Multiplex",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "SubProduct1",
        "ParentID": "b9c54b21-5ab3-4b07-afa6-44756bb2f9b3",
        "ProductID": "373b6c64-6164-4a6b-9e36-e98e646226d8",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "En2",
        "descriptionru": "Ru2",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "SubProduct2",
        "ParentID": "b9c54b21-5ab3-4b07-afa6-44756bb2f9b3",
        "ProductID": "560eaaeb-0f02-423e-9f7a-928ec1ab5a7b",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "SubProduct2",
        "descriptionru": "ПодПродукт2",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "SubProduct3",
        "ParentID": "b9c54b21-5ab3-4b07-afa6-44756bb2f9b3",
        "ProductID": "360b8772-d701-483b-a007-bcb3c18953e2",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Test3",
        "descriptionru": "Тест3",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "SubProduct4",
        "ParentID": "b9c54b21-5ab3-4b07-afa6-44756bb2f9b3",
        "ProductID": "4007b8d5-5c52-46e4-b664-5ccc99fa9c4e",
        "Relation": null,
        "Type": "hardware",
        "colorscheme": "scheme_default",
        "descriptionen": "Test4",
        "descriptionru": "Тест4",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "SubProduct5",
        "ParentID": "b9c54b21-5ab3-4b07-afa6-44756bb2f9b3",
        "ProductID": "35f1420d-82b4-4c84-be5d-364015fdc7c4",
        "Relation": null,
        "Type": "other",
        "colorscheme": "scheme_default",
        "descriptionen": "Test5",
        "descriptionru": "Тест5",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "T2-MI Remultiplexor",
        "ParentID": null,
        "ProductID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_39",
        "descriptionen": "Hardware-software solution for demultiplexing and remultiplexing T2-MI & Multiprogram MPEG-TS streams",
        "descriptionru": "АПК для ремультиплексирования потоков в формате T2MI и многопрограммных потоков MPEG2-TS",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "T2MI-Splitter",
        "ParentID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "ProductID": "05d22726-a776-45a0-8a7a-807028a5b80b",
        "Relation": "bed9125a-a1b3-4cc9-8a0a-20af1b2dfc1c",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "T2MI Splitter Service installation package. Includes server application and WEB UI.",
        "descriptionru": "Дистрибутив службы T2MI Splitter. Включает в себя серверную часть, и WEB интерфейс.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Telegram Notification Service",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "d2422c6a-29f3-4134-ad0a-edf9b396c8d1",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Telegram Notification Service is designed to retrieve messages from StreamLabs MultiScreen monitoring system via Telegram bot.",
        "descriptionru": "Telegram Notification Service  предназначен для получения сообщений от системы мониторинга StreamLabs MultiScreen через Telegram bot.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "Telegram Notification Service user manual",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "fc018dc7-4407-4879-a9b1-b5ede355b1b6",
        "Relation": "d2422c6a-29f3-4134-ad0a-edf9b396c8d1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Telegram Notification Service user manual",
        "descriptionru": "Руководство пользователя Telegram Notification Service",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test",
        "ParentID": "4652f044-2d91-437e-a1da-5dfec1046f42",
        "ProductID": "5b77a440-94df-47d4-92c9-b43216b957b3",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "11111",
        "descriptionru": "11111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "test",
        "ParentID": "2fb0573b-6847-4f37-af52-e9f0942d7aed",
        "ProductID": "7c68c1a5-6bbb-4bea-80f0-2b2ea915c53b",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "1111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test",
        "ParentID": "ca185940-c1b1-43a7-8221-703041350b65",
        "ProductID": "176de0ed-de78-41d0-a654-f56ccd636428",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "en",
        "Name": "test",
        "ParentID": "ed3504b0-3cf9-4b9a-89f1-68acb4381940",
        "ProductID": "85a5ca88-e5ed-4171-b449-fad4de461bfd",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "111",
        "descriptionru": "111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test Product 1",
        "ParentID": "4045f944-6091-4f51-a2ca-439f35c3cda8",
        "ProductID": "716307be-da4f-4677-a5a0-46fc81846b13",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of Test Product 1",
        "descriptionru": "Описание ТЕстового Продукта 1",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test Sub-product",
        "ParentID": "10b44867-3524-4df2-8761-c88dc7b856f1",
        "ProductID": "c105ffd5-0cb4-46ae-ae23-5ab4c48aa119",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "This is test sub-product",
        "descriptionru": "Это тестовый суб-продукт",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test Sub-product",
        "ParentID": "da3eda7e-1e46-4ce2-9d2a-615496aecb8d",
        "ProductID": "499b8539-278e-4877-96fa-db275c69bed5",
        "Relation": null,
        "Type": "hardware",
        "colorscheme": "scheme_default",
        "descriptionen": "Test",
        "descriptionru": "Is test",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test_Product",
        "ParentID": "b3d825f4-7206-4eff-b46e-1f3b2f740512",
        "ProductID": "ab6ac770-a368-4df3-bcc5-d29823236e0c",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Test",
        "descriptionru": "Test",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test_Product",
        "ParentID": "b3d825f4-7206-4eff-b46e-1f3b2f740512",
        "ProductID": "3aa1261f-0ccf-42d3-9b75-92b8fc9e9010",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Test_Product",
        "ParentID": "b3d825f4-7206-4eff-b46e-1f3b2f740512",
        "ProductID": "a065014f-96d4-4f48-a033-e0d385e9b5e0",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "en",
        "Name": "testSub",
        "ParentID": "898faa27-3ee0-4cbe-99c2-10c69d91f979",
        "ProductID": "9ae28df2-b3b1-4fc9-8b12-f772d369f3c6",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "test",
        "descriptionru": "test",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "en",
        "Name": "testSub",
        "ParentID": "4bdd3d82-02a9-4798-8fb2-3ca6a0944311",
        "ProductID": "3d08ae6f-2107-4a54-a406-46dc4fd4cdab",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "ddd",
        "descriptionru": "ddd",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Troubleshooting guide",
        "ParentID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "ProductID": "eea0b888-75a5-4343-8226-aa7483a3745a",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Troubleshooting guide for FM Probe",
        "descriptionru": "Решение проблем при установке и эксплуатации FM Probe",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "TS Analyzer",
        "ParentID": null,
        "ProductID": "00c76d0d-8485-4ed3-a51a-593652840fb2",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_21",
        "descriptionen": "TS/IP/ASI/T2MI Analyzer",
        "descriptionru": "Анализатор TS/IP/ASI/T2MI",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Universal Video capture driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "313ce28a-10d8-4d39-ada8-4149ec039b52",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Universal drivers for video capture cards MS-416, MS2/MS4, MH4LM, MH8",
        "descriptionru": "Универсальные драйвера для плат видеозахвата MS-416, MS2/MS4, MH4LM, MH8",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Upgrade description",
        "ParentID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "ProductID": "5764b7a3-70d6-4cd7-8607-164d85c18120",
        "Relation": null,
        "Type": "document",
        "colorscheme": null,
        "descriptionen": "Update description",
        "descriptionru": "Описание процесса загрузки прошивки FM Probe",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "USB CryptoKey - driver",
        "ParentID": "521eaa49-d4a1-4ff8-b8f5-f81815e1178d",
        "ProductID": "df2cfd7b-679b-4296-a5de-9df1c8d94237",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for USB CryptoKey",
        "descriptionru": "Драйвера для USB-ключа ПО StreamLabs",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "USB GPIO - driver",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "4e9deecf-cb48-4106-941e-c2bad2aba208",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "Driver package for USB GPIO",
        "descriptionru": "Драйвера для устройства USB GPIO",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "User manual",
        "ParentID": "f53eb514-b355-41d8-805c-df3cb2dc26dc",
        "ProductID": "296854e4-60ee-4e0a-9350-b52cb58ad39d",
        "Relation": "79f5bc2d-d7f7-45f3-a417-ab9a812b42ce",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "User manual",
        "descriptionru": "Руководство пользователя",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "User Manual",
        "ParentID": "3c5b9f18-5152-481c-9682-bf35b92aeb26",
        "ProductID": "4db24d76-ac8c-4d4a-91de-8f98fdd8fd72",
        "Relation": "05d22726-a776-45a0-8a7a-807028a5b80b",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream T2MI Splitter user manual.",
        "descriptionru": "Руководство пользователя системы Stream T2MI Splitter.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "User manual",
        "ParentID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "ProductID": "240a7d27-1165-4d7e-a143-0ba2743722ad",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "User manual for FM Probe (Russian only)",
        "descriptionru": "Руководство по эксплуатации FM Probe",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "en",
        "Name": "User manual Stream MultiRec 3.X",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "b1446289-982b-442a-98f6-15aa3b476a43",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "User manual Stream MultiRec 3.X",
        "descriptionru": "User manual Stream MultiRec 3.X (ENG)",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "V365_test",
        "ParentID": "1a6bf620-592a-447c-9fb8-196e9f842263",
        "ProductID": "ee767809-ee8a-4eb3-9520-7ee8225d3968",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "V365_test",
        "descriptionru": "V365_test",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "VAdBrush",
        "ParentID": null,
        "ProductID": "1943e0e3-d028-4773-bf5b-3a9730519de2",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_1",
        "descriptionen": "VAdBrush",
        "descriptionru": "VAdBrush",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "Virtual Keyboard",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "75ea1547-fabe-4faa-9f52-6bba4c0a1814",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Programmable keyboards designed for easy navigation between channels in pre-set MultiScreen configurations.",
        "descriptionru": "Программируемая клавиатура для быстрой навигации по каналам предустановленных конфигураций MultiScreen.",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "VMedia 5",
        "ParentID": null,
        "ProductID": "c721ce2b-028e-4aea-9fc2-0ecbe902b363",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_9",
        "descriptionen": "VMedia 5 product",
        "descriptionru": "VMedia 5 продукт",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "VMedia 5",
        "ParentID": "c721ce2b-028e-4aea-9fc2-0ecbe902b363",
        "ProductID": "04c9073d-7d8d-400c-8d7d-fe6bbb42c6f9",
        "Relation": null,
        "Type": "software",
        "colorscheme": null,
        "descriptionen": "VMedia 5",
        "descriptionru": "VMedia 5",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "VMedia User manual ENG",
        "ParentID": "c721ce2b-028e-4aea-9fc2-0ecbe902b363",
        "ProductID": "a15c8378-8f16-489d-95c3-19d46c5befc9",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "VMedia User manual ENG",
        "descriptionru": "VMedia Руководство пользователя ENG",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "VMedia Руководство пользователя RUS",
        "ParentID": "c721ce2b-028e-4aea-9fc2-0ecbe902b363",
        "ProductID": "8be8743d-44f8-4ae0-99be-6414af585bb9",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "VMedia User manual RUS",
        "descriptionru": "VMedia Руководство пользователя RUS",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "Vplay",
        "ParentID": null,
        "ProductID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_40",
        "descriptionen": "Multichannel broadcast programming, creating and overlaying graphic designs",
        "descriptionru": "Многоканальное формирование сеток вещания, создание и наложение графического оформления",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "VPlay 4 Documentation",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "2a8cd71a-8690-4509-ba84-a9a169dc35da",
        "Relation": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "VPlay 4 user guide.",
        "descriptionru": "Руководство пользователя системы VPlay 4.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "Vplay 4 Documentation Eng",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "460e27d6-f0aa-4018-bbe6-038141305f19",
        "Relation": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "User Manual",
        "descriptionru": "Руководство пользователя системы VPlay 4. ENG",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "VPlay 5",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Relation": null,
        "Type": "software",
        "colorscheme": null,
        "descriptionen": "Playout software for SD/HD/UHD channels.",
        "descriptionru": "Многофункциональное программное обеспечение для организации многоканального вещания/врезки в форматах SD/HD/UHD.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "VPlay 5 Documentation ENG",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "c05e1bb6-ccfb-458f-b29e-4851970a913b",
        "Relation": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Type": "document",
        "colorscheme": null,
        "descriptionen": "VPlay 5 Documentation ENG",
        "descriptionru": "VPlay 5 Documentation ENG",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "VPlay 5 Documentation RUS",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "5a4799f4-213e-468c-b7f6-f609a4d363ab",
        "Relation": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Type": "document",
        "colorscheme": null,
        "descriptionen": "VPlay 5 Documentation ENG",
        "descriptionru": "VPlay 5 Документяция RUS",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Vplay 5 File Format Support",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "4ae4b91f-a1aa-4c59-8ad8-6de81f38ce21",
        "Relation": "ddc12e75-e90d-4af2-a1b6-9a04313cd6c8",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Vplay 5 File Format Support",
        "descriptionru": "Vplay 5 File Format Support",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "Vplay v.4",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Relation": null,
        "Type": "software",
        "colorscheme": null,
        "descriptionen": "Playout software for SD/HD channels.",
        "descriptionru": "VPlay - многофункциональное программное обеспечение для организации многоканального вещания/врезки в форматах SD/HD.",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "VRec",
        "ParentID": null,
        "ProductID": "1d9655fc-30de-4b18-9fd1-8b6d3e6a16a8",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_9",
        "descriptionen": "Multi channel ingest",
        "descriptionru": "Многоканальный инжест",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "VRec",
        "ParentID": "1d9655fc-30de-4b18-9fd1-8b6d3e6a16a8",
        "ProductID": "accdf1a9-f235-4387-a2e2-868a218fce64",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "VRec - multifunctional software for organizing multi-channel recording in SD/HD formats.",
        "descriptionru": "VRec - многофункциональное программное обеспечение для организации многоканальной записи в форматах SD/HD.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "VRec Documentation",
        "ParentID": "1d9655fc-30de-4b18-9fd1-8b6d3e6a16a8",
        "ProductID": "9ac4848c-a45d-4488-bd43-d49207ea0abf",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "VRec 4 Documentation Eng",
        "descriptionru": "Руководство пользователя системы VRec",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "en",
        "Name": "VRec Documentation Eng",
        "ParentID": "1d9655fc-30de-4b18-9fd1-8b6d3e6a16a8",
        "ProductID": "5a638870-bc1b-4009-bfe4-dd3a75d1e475",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "VRec 4 Documentation Eng",
        "descriptionru": "Руководство пользователя системы VRec",
        "isDeleted": false
    },
    {
        "AccessType": null,
        "Language": "all",
        "Name": "VSDK",
        "ParentID": null,
        "ProductID": "ad408113-410f-4597-b93b-a1edef7a2595",
        "Relation": null,
        "Type": null,
        "colorscheme": "scheme_7",
        "descriptionen": "VSDK",
        "descriptionru": "VSDK",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "06590019-1c61-41fd-9ba9-6e419618617e",
        "ProductID": "db878556-c8a0-49e5-b28f-a3fd41f2a527",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "11112 3456 8904333  33 333 33333333333g  3333333 333 33 3333333 3333 333 3333333 33333 333333 333333 3333 33 333333 3333333 333333 33333333  3333333 33333333333 33333333333 5n6466 6456 464645 64566 45646 656 456465 54646 546456 6565464 654645 56456 5656 56",
        "descriptionru": "11112 3456 8904333  33 333 33333333333g  3333333 333 33 3333333 3333 333 3333333 33333 333333 333333 3333 33 333333 3333333 333333 33333333  3333333 33333333333 33333333333 5n6466 6456 464645 64566 45646 656 456465 54646 546456 6565464 654645 56456 5656 56",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "9e7df3a0-c461-4116-9244-6a111e4b3a2e",
        "ProductID": "c7759b7f-0286-4ea2-ac66-7ff8fe128c17",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "1234566",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "fd65d45d-c158-407c-9863-1ce67c9a425f",
        "ProductID": "d32b9543-447e-42d4-8703-818f888aa2ea",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "5d0a4379-1c4d-4e37-a49f-13175d279dba",
        "ProductID": "0ab7c530-72eb-4447-83d1-819f19d77158",
        "Relation": null,
        "Type": "other",
        "colorscheme": "scheme_default",
        "descriptionen": "11111",
        "descriptionru": "111111",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "ea876187-00d0-4c33-8fb9-abd8b0977343",
        "ProductID": "511257d6-9e96-4cf4-84d2-ac952cdf56e2",
        "Relation": null,
        "Type": "hardware",
        "colorscheme": "scheme_default",
        "descriptionen": "31232",
        "descriptionru": "213213",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "167b1629-7518-422d-bfc7-1c69bff2fd76",
        "ProductID": "bd7dbfd6-ace2-469e-bb78-b04c685ad1ea",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "9996671e-bb8a-406b-92aa-4a2bee56313f",
        "ProductID": "f9f540cb-8aa6-43a7-8258-b9a03405c7fe",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "en",
        "Name": "WTesting Product",
        "ParentID": "02930814-5a2b-489c-9bfa-fce4b07c2d68",
        "ProductID": "d7f7c0b5-3dc9-4207-be8b-366cc3ea8bcd",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "1111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "fd65d45d-c158-407c-9863-1ce67c9a425f",
        "ProductID": "edd35c92-91f0-4aa7-8a4a-29a2d0acf99e",
        "Relation": null,
        "Type": "driver",
        "colorscheme": "scheme_default",
        "descriptionen": "11111",
        "descriptionru": "11111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "6abbe1b5-4405-4e7c-bae4-4fd0e5ba70dc",
        "ProductID": "7dbb5e6e-f4e6-4cc9-aef1-0a67e87b1681",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "23de48ae-5f76-433d-ae11-e6c1e1408fd3",
        "ProductID": "bf79bccb-228a-478e-87ef-1c31b2b15cbb",
        "Relation": null,
        "Type": "firmware",
        "colorscheme": "scheme_default",
        "descriptionen": "12345",
        "descriptionru": "12345",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "03e0fe60-2ee0-4d40-8ac7-901b6db798ed",
        "ProductID": "c7ffcff6-c60a-4b3f-9601-158d658233c7",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "This Is QA Test",
        "descriptionru": "This Is QA Test",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "28de5a16-719b-45d3-ac80-44ed9da195d8",
        "ProductID": "e053d043-7a6b-473c-af77-6aab68bb8938",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "1111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "df3374c9-67cb-4ff7-beda-313405c41c29",
        "ProductID": "132cc370-c575-4d60-8759-646b956d1ce5",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "1234356",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "b088639b-552e-496e-a2ff-97a8d551c6ca",
        "ProductID": "9b41015b-fd18-4150-b043-4e4344b2c9a6",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "faa52195-aeb2-485b-a823-9aeb0180e632",
        "ProductID": "3301a2c7-608e-4e6f-b730-5a1229c0a429",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "12345",
        "descriptionru": "12345",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "abd3528d-876f-4279-80ea-3d2a5a4f52aa",
        "ProductID": "0b7def3f-c1f1-4712-a88d-dec73f6dcba1",
        "Relation": null,
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "123456",
        "descriptionru": "123456",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product",
        "ParentID": "fd65d45d-c158-407c-9863-1ce67c9a425f",
        "ProductID": "9898cd59-1937-42ff-94df-e92024f16c21",
        "Relation": null,
        "Type": "hardware",
        "colorscheme": "scheme_default",
        "descriptionen": "1111",
        "descriptionru": "1111",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "all",
        "Name": "WTesting Product4",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "f34fd7fb-b6da-4d02-9af0-0dc6277bc6bd",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "4444",
        "descriptionru": "44444",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "all",
        "Name": "WTesting Product5",
        "ParentID": "d4135028-982c-4525-ae94-6864aa86d990",
        "ProductID": "307cc545-fbee-4d65-9761-3307f8082395",
        "Relation": null,
        "Type": "other",
        "colorscheme": "scheme_default",
        "descriptionen": "44444",
        "descriptionru": "444444",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Документация по установке драйверов и перепрошивке видеоплат",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "fee160a5-1fdd-431d-a0a5-3abd6683cb82",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of driver and firmware update",
        "descriptionru": "Документация по установке драйверов и перепрошивке видеоплат/устройств Stream Labs",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Документация по устройствам USB GPIO",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "235a07a5-25b6-4d34-a3bc-b30a9c5c7961",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of USB GPIO",
        "descriptionru": "Документация по устройствам USB GPIO",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Инструкция по техническому обслуживанию.",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "0502fb3e-4382-4181-9eda-fbf33c298172",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Probe maintenance guide",
        "descriptionru": "Инструкция по техническому обслуживанию, хранению, транспортированию.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Инструкция по установке для ЦСД.",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "4e0116c6-27c6-4a91-a9ba-617c65d49853",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream Multiprobe installation guide.",
        "descriptionru": "Инструкция по установке Stream Multiprobe для Центра Сбора Данных.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Инструкция. Блок приема и анализа сигналов БПАС.",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "40c94bda-cea3-49f5-bdec-025a3d684468",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Guide",
        "descriptionru": "Инструкция по настройке устройств. Блок приема и анализа сигналов БПАС",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "История изменений",
        "ParentID": "8f9ecbc9-b26f-46c8-9bdf-207959187a72",
        "ProductID": "1e5db81b-1bed-418a-8ff3-5fb3bbe36efd",
        "Relation": null,
        "Type": "document",
        "colorscheme": null,
        "descriptionen": "Change log",
        "descriptionru": "История изменений версий прошивки для FM Probe",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Модуль распознавания статических изображений",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "d976354f-ac40-4962-afb3-dc6211b0ff6d",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Detecting and logging appearences of pre-determined static images in incoming videosignals",
        "descriptionru": "Нахождение и документирование случаев появления заданных статических изображений в видео",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Мониторинг сервисов через панель состояния",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "9a166046-4806-430e-a34c-8ce7e90d1a2b",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Instruction manual on set-up and implementation of monitoring over State Panel",
        "descriptionru": "Руководство по настройке и осуществелнию мониторинга через панель состояния",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Настройка визуализации сервисов",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "1a124b2c-5c95-4070-87f0-c739e30d65cb",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Detailed description of the process from connecting Multi Monitor to MultiScreen Servers to the visualization of incoming videostreams and videosignals on a videowall",
        "descriptionru": "Подробное описание действий от подключения приложения Multi Monitor к серверам MultiScreen до визуализации входных видеопотоков и видеосигналов на видеостене",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Описание видеоплат",
        "ParentID": "8b359fbd-ad54-4715-a917-82aaea1a95e5",
        "ProductID": "f8aad1f6-d13a-4cbe-aada-f25fe35494e6",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of video cards",
        "descriptionru": "Описание видеоплат",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Описание системы Stream MultiScreen, установка ПО",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "82822c0e-94d7-463c-b3a7-d5601535bed7",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Overview of the Stream MultiScreen system, Software Installation",
        "descriptionru": "Описание системы Stream MultiScreen, обзор программных компонентов и их установка",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Погодный датчик",
        "ParentID": "7bf6b57c-4266-44a6-b5ad-c655e1798105",
        "ProductID": "465743d2-0816-4692-ac61-bc3fec797826",
        "Relation": "cd9afd45-91b0-498b-969e-1c50efb9892e",
        "Type": "software",
        "colorscheme": "scheme_default",
        "descriptionen": "Погодный датчик \"Тундра\"",
        "descriptionru": "weather sensor \"Tundra\"",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Приложение к руководству пользователя.",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "f03f5109-7cbc-4fcd-8e8d-d07b1d88f22b",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "additional to user manual",
        "descriptionru": "Приложение к руководству пользователя.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство по настройке удаленной клавиатуры",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "86cf4c16-a430-435c-81cd-4e487f47f15e",
        "Relation": "75ea1547-fabe-4faa-9f52-6bba4c0a1814",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Configuring software and hardware keyboard for remote control",
        "descriptionru": "Конфигурирование программной и аппаратной клавиатуры для удаленного контроля",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство по работе с метками SCTE-104 и SCTE-35",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "95298230-0bc6-4040-9a8e-898885ed3739",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Description of functionality for logging and processing SCTE-104 and SCTE-35 messages",
        "descriptionru": "Описание функционала для документирования и обработки рекламных меток SCTE-104 и SCTE-35",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство по работе с модулем SNMP сollector",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "aa2dd7e5-ec42-4149-bf08-8020859ef6ff",
        "Relation": "618afd24-fdf7-4401-aa9c-011d8ef31a2f",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "SNMP сollector manual",
        "descriptionru": "SNMP сollector руководство пользователя",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство по работе с модулем SNMP сollector",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "18b278ff-e826-4ece-9414-2af2e742307e",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "SNMP Collector documentation",
        "descriptionru": "SNMP Collector документация",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство по тревожным событиям",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "eaad1b53-137c-44d2-b31e-3460e1caec45",
        "Relation": "b5a3e7b9-fc43-4fb3-9701-0b17175be7f1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Detailed description of configuring alarms",
        "descriptionru": "Подробное описание конфигурирования тревожных событий",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "РУКОВОДСТВО ПО ЭКСПЛУАТАЦИИ",
        "ParentID": "b2f531aa-46f9-472c-9405-a17d2db27c19",
        "ProductID": "4b697c93-1d65-4075-ae0d-2201623833bb",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Manual",
        "descriptionru": "РУКОВОДСТВО ПО ЭКСПЛУАТАЦИИ",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Руководство по эксплуатации.",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "82619b7f-c95a-4df1-9988-039899660c4a",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "probe userguide",
        "descriptionru": "Руководство по эксплуатации. (БПАС) Блок приема и анализа сигналов.",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство пользователя",
        "ParentID": "f53eb514-b355-41d8-805c-df3cb2dc26dc",
        "ProductID": "fdee6e75-5132-4a02-b30f-ccaf334a35c7",
        "Relation": "79f5bc2d-d7f7-45f3-a417-ab9a812b42ce",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "User manual",
        "descriptionru": "Руководство пользователя",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Руководство пользователя Multirec 3.0",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "909223ae-0a7c-4f43-afd7-27a987d23e45",
        "Relation": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Multirec 3.0 manual",
        "descriptionru": "Видео-серверы многоканальной записи ТВ и радио эфира  Stream MultiRec  v. 3.0",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Руководство пользователя Stream MultiRec 3.X",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "fc281122-b019-4cb4-b5a9-deb47f7f8f28",
        "Relation": null,
        "Type": "document",
        "colorscheme": null,
        "descriptionen": "User manual Stream MultiRec 3.X (RUS)",
        "descriptionru": "Руководство пользователя Stream MultiRec 3.X",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Руководство пользователя Stream MultiScreen 5.X",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "b88afe59-ff4a-4318-bf27-efec1f119b3c",
        "Relation": "fb34b210-05bc-40e6-9fc2-95c412c68317",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream MultiScreen 5.X manual",
        "descriptionru": "Руководство пользователя Stream MultiScreen 5.X",
        "isDeleted": false
    },
    {
        "AccessType": "Public",
        "Language": "ru",
        "Name": "Руководство пользователя Telegram Notification Service",
        "ParentID": "57b92700-cfef-4cee-95c6-65fde2956947",
        "ProductID": "0c4f9f38-8d64-4873-802f-04d930138057",
        "Relation": "d2422c6a-29f3-4134-ad0a-edf9b396c8d1",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Telegram Notification Service user manual",
        "descriptionru": "Руководство пользователя Telegram Notification Service",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Руководство системного программиста. / Multiprobe БПАС",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "bfaeff3d-e1df-44d9-88f6-5a3f39a8d224",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Multiprobe. System programmer's guide",
        "descriptionru": "Руководство системного программиста. / Multiprobe БПАС",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Сервер резервирования / Руководство пользователя.",
        "ParentID": "87926c8d-4f6c-4d2d-a0f9-a3d6340f26bb",
        "ProductID": "2d32b8f7-fca1-4630-8542-b8355dc2dc89",
        "Relation": "4fcf5f95-b30f-47cc-8db3-82571572c2d8",
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "manual",
        "descriptionru": "Принцип работы сервера резервирования.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Спецификация",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "78d3d58d-771a-473e-a882-56363ff109d9",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "specifiaction",
        "descriptionru": "Спецификация прогрмного комлекса Stream Multiprobe для ЦСД.",
        "isDeleted": false
    },
    {
        "AccessType": "Subscription",
        "Language": "ru",
        "Name": "Формуляр / ПК Stream Multiprobe для \"БПАС\".",
        "ParentID": "d0c64aa9-b0e8-4405-afe7-fba7285e533d",
        "ProductID": "11732ba1-5164-46c9-b686-a6ccf6a66c0b",
        "Relation": null,
        "Type": "document",
        "colorscheme": "scheme_default",
        "descriptionen": "Stream Multiprobe Datasheet",
        "descriptionru": "Формуляр. Программный комплекс Stream Multiprobe  для \"БПАС\" - Блоков Приема и Анализа Сигналов.",
        "isDeleted": false
    }
]